title: "Centria Linux Essentials"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    line_numbers: false
permalink: pretty
baseurl: "/lx"
url: "https://averkoc.github.io"
github:
  username: averkoc
  repository_name: lx

